version: '3.8'

services:
  backend:
    build: ./mern-auth-server
    ports: 
      - "5555:5555"
    env_file:
      - ./mern-auth-server/.env
    depends_on: 
      - mongodb

  frontend: 
    build: ./mern-auth-web
    ports: 
      - "3000:80"
    depends_on: 
      - backend

  mongodb: 
    image: mongodb
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db


volumes:
  mongodb_data: